package ui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 * @creed: Here be dragons !
 * @author: EzioQAQ
 * @Time: 2019-04-20 18:07
 */
public class GenForm {
    public JPanel mainPanel;
    public JTextField daoSuffix;
    public JTextField daoAnnotation;
    public JCheckBox createXml;
    public JTextField serviceAnnotation;

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow",
            "center:d:noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow,top:3dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setPreferredSize(new Dimension(0, 130));
        CellConstraints cc = new CellConstraints();
        mainPanel.add(panel1, cc.xy(1, 1));
        panel1.setBorder(BorderFactory.createTitledBorder("Dao的配置"));
        final JLabel label1 = new JLabel();
        label1.setPreferredSize(new Dimension(170, 16));
        label1.setText("Dao的后缀(默认XXXDao)");
        panel1.add(label1, cc.xy(1, 1));
        daoSuffix = new JTextField();
        panel1.add(daoSuffix, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        daoAnnotation = new JTextField();
        panel1.add(daoAnnotation, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        final JLabel label2 = new JLabel();
        label2.setText("Dao注解(默认@Mapper)");
        panel1.add(label2, cc.xy(1, 3));
        final JLabel label3 = new JLabel();
        label3.setText("Dao相对应XML的文件");
        panel1.add(label3, cc.xy(1, 5));
        createXml = new JCheckBox();
        createXml.setPreferredSize(new Dimension(85, 20));
        createXml.setSelected(true);
        createXml.setText("默认创建");
        panel1.add(createXml, cc.xy(3, 5));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:noGrow"));
        panel2.setPreferredSize(new Dimension(0, 90));
        mainPanel.add(panel2, cc.xy(1, 3));
        panel2.setBorder(BorderFactory.createTitledBorder("Service的配置"));
        final JLabel label4 = new JLabel();
        label4.setPreferredSize(new Dimension(170, 16));
        label4.setText("Service注解(默认@Service)");
        panel2.add(label4, cc.xy(1, 1));
        serviceAnnotation = new JTextField();
        panel2.add(serviceAnnotation, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
